//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoPicture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoPicture.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de créer un VideoCaptureDevice.
        /// </summary>
        internal static string ImpossibleCreerVCDevice {
            get {
                return ResourceManager.GetString("ImpossibleCreerVCDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ouvrir la vidéo.
        /// </summary>
        internal static string ImpossibleOpenRecordedVideo {
            get {
                return ResourceManager.GetString("ImpossibleOpenRecordedVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;enregistrer la vidéo.
        /// </summary>
        internal static string ImpossibleRecordVideo {
            get {
                return ResourceManager.GetString("ImpossibleRecordVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune caméra trouvée.
        /// </summary>
        internal static string NoCamera {
            get {
                return ResourceManager.GetString("NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun VideoCapabilities trouvé.
        /// </summary>
        internal static string NoVCapabilitiesFound {
            get {
                return ResourceManager.GetString("NoVCapabilitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune caméra configurée.
        /// </summary>
        internal static string PasDeCameraConfig {
            get {
                return ResourceManager.GetString("PasDeCameraConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin où enregistrer les vidéos invalide.
        /// </summary>
        internal static string PasDePathRecordPictures {
            get {
                return ResourceManager.GetString("PasDePathRecordPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin où enregistrer la vidéo invalide.
        /// </summary>
        internal static string PasDePathRecordVideo {
            get {
                return ResourceManager.GetString("PasDePathRecordVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune résolution configurée.
        /// </summary>
        internal static string PasDeResolutionCamConfig {
            get {
                return ResourceManager.GetString("PasDeResolutionCamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La résolution configurée n&apos;est pas disponible.
        /// </summary>
        internal static string PasDeResolutionCorrespondante {
            get {
                return ResourceManager.GetString("PasDeResolutionCorrespondante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string StartRecVideo {
            get {
                return ResourceManager.GetString("StartRecVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopRecVideo {
            get {
                return ResourceManager.GetString("StopRecVideo", resourceCulture);
            }
        }
    }
}
